# Generated by Django 3.2 on 2021-07-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.CharField(default='Неизвестно', max_length=255)),
                ('cipher', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('Tetr', 'Четвероевангелие'), ('Lect', 'Лекционарий'), ('unknown', 'неизвестно')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('list_number', models.CharField(max_length=5, unique=True)),
                ('chapter', models.CharField(max_length=2)),
                ('verse', models.CharField(max_length=2)),
                ('lec_type', models.CharField(choices=[('le', 'полный'), ('Lesk', 'краткий'), ('Lesel', 'праздничный'), ('unknown', 'неизвестно')], max_length=15)),
                ('lec_part_type', models.CharField(choices=[('sin', 'Синаксарь'), ('men', 'Менологий')], max_length=15)),
                ('lec_month_type', models.CharField(choices=[('St', 'сентябрь'), ('Ok', 'октябрь'), ('Nw', 'ноябрь'), ('Dec', 'декабрь'), ('Ja', 'январь'), ('Feb', 'февраль'), ('Mar', 'март'), ('Apr', 'апрель'), ('May', 'май'), ('Jun', 'июнь'), ('Jul', 'июль'), ('Aug', 'август'), ('unknown', 'неизвестно')], max_length=15)),
                ('gospel', models.CharField(choices=[('Matthew', 'Матфея'), ('Luke', 'Луки'), ('Mark', 'Марка'), ('John', 'Иоанна'), ('unknown', 'неизвестно')], max_length=7)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='v1.manuscript')),
            ],
        ),
    ]
