# Generated by Django 3.1.7 on 2021-04-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.CharField(default='Неизвестно', max_length=255)),
                ('gospel', models.CharField(blank=True, choices=[('Matthew', 'Матфея'), ('Luke', 'Луки'), ('Mark', 'Марка'), ('John', 'Иоанна')], max_length=7, null=True)),
                ('lectionary', models.BooleanField(default=False)),
                ('lectionary_description', models.JSONField(blank=True, null=True)),
                ('description', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='v1.manuscript')),
            ],
        ),
    ]
