# Generated by Django 3.2 on 2021-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='chapter',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lec_month_type',
            field=models.CharField(blank=True, choices=[('St', 'сентябрь'), ('Ok', 'октябрь'), ('Nw', 'ноябрь'), ('Dec', 'декабрь'), ('Ja', 'январь'), ('Feb', 'февраль'), ('Mar', 'март'), ('Apr', 'апрель'), ('May', 'май'), ('Jun', 'июнь'), ('Jul', 'июль'), ('Aug', 'август'), ('unknown', 'неизвестно')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lec_part_type',
            field=models.CharField(blank=True, choices=[('sin', 'Синаксарь'), ('men', 'Менологий')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lec_type',
            field=models.CharField(blank=True, choices=[('le', 'полный'), ('Lesk', 'краткий'), ('Lesel', 'праздничный'), ('unknown', 'неизвестно')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='list_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='image',
            name='verse',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
