# Generated by Django 3.2 on 2021-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20210712_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='lec_type',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='lec_type',
            field=models.CharField(blank=True, choices=[('le', 'полный'), ('Lesk', 'краткий'), ('Lesel', 'праздничный'), ('unknown', 'неизвестно')], max_length=15, null=True),
        ),
    ]
