# Generated by Django 3.2 on 2021-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20210714_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='verse_quote',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
