# Generated by Django 3.2 on 2021-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20210714_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='img_description',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='man_description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='cipher',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='creation_date',
            field=models.CharField(default='Неизвестно', max_length=25),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='storage',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
