# Generated by Django 3.2 on 2021-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20210718_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='gospel',
            field=models.CharField(choices=[('Matthew', 'Матфея'), ('Luke', 'Луки'), ('Mark', 'Марка'), ('John', 'Иоанна'), ('unknown', 'неизвестно')], max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='lec_part_type',
            field=models.CharField(blank=True, choices=[('sin', 'Синаксарь'), ('men', 'Менологий'), ('unknown', 'Неизвестно')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='verse_quote',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='cipher',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='man_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='type',
            field=models.CharField(choices=[('Tetr', 'Четвероевангелие'), ('Lect', 'Лекционарий'), ('unknown', 'неизвестно')], max_length=20),
        ),
    ]
