# Generated by Django 3.2 on 2021-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20210719_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='man_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
