# Generated by Django 3.2 on 2021-07-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_manuscript_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='part_of_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
